[package]
name = "rust-cas"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
number-theory = "0.0.6"
#{ git = "https://github.com/JASory/ENT" }
